site_name: Gamifica Requisitos
site_url: https://mdsreq-fga-unb.github.io/2023.1-GamificaRequisitos/

nav:
  - Home: index.md
  - Unidade 1:
    - Visão do Produto: unidade1/visao_produto.md
    - Visão do Projeto: unidade1/visao_projeto.md
    - Processo de Desenvolvimento de software: unidade1/processo-software.md
    - Lições Aprendidas: unidade1/licoes_aprendidas.md
    - Bibliografia: unidade1/bibliografia.md

    - Unidade 2:
      - Produto Backlog: unidade2/backlog.md
      - MVPs: unidade2/mvps.md
      - URPS+: unidade2/urps.md
      - Lições Aprendidas: unidade2/licoes_aprendidas.md
      - Bibliografia: unidade2/bibliografia.md

theme:
  name: material
  icon:
    logo: material/gamepad-square 
    favicon: images/favicon.png
  palette:
    - scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Modo noturno
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Modo claro

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences